### ISSUE TITLE
🚀 Roadmap for 1.0

### ISSUE THREAD

**Issue by rozenmd** [OnlineOrNot/onlineornot#16]
### Describe the solution

- [x] BREAKING CHANGE: Move the checks commands under `onlineornot checks ...`
- [x] Implement `onlineornot checks new`
- [x] Implement `onlineornot checks delete <id>`
- [x] Implement `onlineornot login`
- [x] Implement `onlineornot docs`
- [x] Implement `onlineornot billing`
- [x] Add docs under https://onlineornot.com/docs/

**Comment by rozenmd** [comment]
Ready to go.
